### ISSUE TITLE
Consider Removing Type Variable of `Bytes`

### ISSUE THREAD

**Issue by keyan-m** [mpizenberg/elm-cardano#29]
This discussion started on Discord (and a continuation of #12) as I was struggling to define an opaque datatype for `PolicyId` such that its encoders/decoders enforced exactly 28 bytes to be stored underneath—with little disruption to other datatypes. However, after sleeping on the idea a bit more, I see now that this can be achieved like this:
```elm
import Cardano.Bytes.Comparable exposing (Any, Bytes)

type PolicyId =
    PolicyId (Bytes Any)

type AssetName =
    AssetName (Bytes Any)
-- etc., all opaque
```

The different approach I had in mind was very similar, it only removed the phantom type of `Bytes`:
```elm
-- Cardano.Bytes.Comparable
type Bytes = Bytes String

-- Cardano.MultiAssets
type PolicyId =
    PolicyId Bytes

type AssetName =
    AssetName Bytes
-- etc., all opaque
```

I believe both of these approaches can lead to many repetitions for their utility functions like `jsonDecoder` etc. (as pointed out by @mpizenberg).

If this really is the case (i.e. there is little difference between the two approaches), perhaps we can only ask whether `Bytes` really need to carry additional type information.

**Comment by keyan-m** [comment]
After learning Aiken a bit more, and also getting more familiar with `cardano-api` codebase, I see that both use phantom types for byte array representations.

**Comment by mpizenberg** [comment]
Yeah, so the idea is that the phantom type marker on the side of Bytes would prevent people from building or using these bytes incorrectly. These constraints imply that of course we get rid of `Bytes.fromStringUnchecked : String -> Bytes a` in the public api. Same for other functions that can return `Bytes a` with any `a` where there isn’t first a constraint on the inputs somehow. Then we would need to expose some public constructors. Things like:

```elm
policyIdFromHex : String -> Maybe (Bytes PolicyId)
```

And those functions can use whatever internally. Meaning we could move the raw definition of `Comparable.Bytes` into a non-exposed module, and just the exposed `Bytes` type would just wrap the non-exposed one.

I haven’t thought through all the details yet, but it seems like if/when we want to remove all escape hatches from public APIs, there should be a way to do it. I’m just not sure if the extra friction is worth it for the time being?

Does it make sense?

**Comment by keyan-m** [comment]
Thanks, I understand the reasoning. I'm just not sold yet as I've hadn't a great dev experience with it so far.
