### ISSUE TITLE
Making an elm-cardano binary

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-cardano#41]
Currently, we are building a library, but it hasn’t been published as a package yet. But even once it is published, it won’t be enough to use as-is. There are a few difficulties that we need to handle, including:

- There is a need for specific JS code to understand some of the Json encoders/decoders in elm-cardano.
- There is some port logic that needs to be directly provided, such as handling a CIP30 wallet connection, or an Ogmios websocket connection.
- There is a need to provide some primitives, such as hashing or plutus script evaluation.
- People might want to run some elm-cardano code in Node intead of in a web browser

## Specific JS encoders/decoders

All big numbers must be handled properly when encoding from elm to a JS Value. We can’t encode it as an integer, so we define a standard: `{bignum: "100000000000000"}`. The JS side of things must be aware of this to properly convert those to JS bignum, so we provide code for that.

The Cip30 modules and Ogmios6 modules define specific request types when encoding requests as JS values. The JS side must be aware of this so we provide code for that too.

## Port logic

In addition to specific encoding/decoding of some elm-cardano values, the ports dealing with these communications also need some specific code. For example, the Ogmios ports need to setup and handle a websocket connection with Ogmios.

## Pure primitives

The elm-cardano library needs to perform some pure computation, for which there doesn’t exist yet Elm code. For example, we need to evaluate transactions to obtain its cpu/mem costs, which are needed when building a transaction.

Three solutions here:

1. Writing that pure code in Elm. This is the long term solution, but it is to much effort to do now for everything that’s needed. For example, plutus evaluation needs crypto primitives that would take way too long to implement.
2. Forcing the API to use commands and ports. It would be a nightmare for some use cases. For example, for transaction building, that would be super anoying, because script evaluation is needed in the Tx building loop, multiple times.
3. Patching Elm kernel code to provide some of these primitives directly. It’s hacky but doable, I’ve done some kernel patching already in elm-test-rs. It’s also what elm-test does.

## Running in Node instead of Browser

Some people already asked about it and I think it is a reasonable use case. But by default, elm code is only runable in a browser. It’s possible however to run it in Node, since that’s exactly what we do when running tests. Here again, I have some experience modifying an elm program to run it in Node (or Deno) thanks to elm-test-rs.

# Summary

It seems to me, the most dev-friendly approach to solve all these problems would be to provide an elm-cardano binary. Just like elm-test-rs, this binary would depend on an elm installation, but would be called directly.

So instead of calling `elm make ...`, we could just call `elm-cardano make ...` and it would do all the things that are needed:
 - including the relevant JS code
 - patching the kernel code to add some primitives such as script evaluation
 - make it browser or node compatible depending on the main program type

**Comment by mpizenberg** [comment]
I thought it would be super cool to write this binary in Roc. But I’ve just spent a couple days following closely its dev status and it would be a bad idea unfortunately. There are still major changes coming to the tasks system and to parametric modules that are incoming. And following these discussions made me realize it can change a lot of existing code.

So I’ll settle for using Rust, just like elm-test-rs, if that approach seems fine.

**Comment by rvcas** [comment]
I see, yes that makes sense

**Comment by mpizenberg** [comment]
Done in #49
